# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('safe', models.DecimalField(decimal_places=10, max_digits=19)),
                ('info', models.DecimalField(decimal_places=10, max_digits=19)),
                ('service', models.DecimalField(decimal_places=10, max_digits=19)),
                ('add_service', models.DecimalField(decimal_places=10, max_digits=19)),
                ('investments', models.DecimalField(decimal_places=10, max_digits=19)),
                ('transfers', models.DecimalField(decimal_places=10, max_digits=19)),
                ('bank_contact', models.DecimalField(decimal_places=10, max_digits=19)),
                ('terminal_availability', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
