# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='accounts',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
    ]
