# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_bank_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Ul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('info', models.DecimalField(decimal_places=10, max_digits=19)),
                ('bank_contact', models.DecimalField(decimal_places=10, max_digits=19)),
                ('business_func', models.DecimalField(decimal_places=10, max_digits=19)),
                ('safe', models.DecimalField(decimal_places=10, max_digits=19)),
                ('currency_work', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
